AI: debug : Auto-play stopped. Server Error (500):
<!doctype html>
<html lang=en>
  <head>
    <title>AttributeError: &#39;Game&#39; object has no attribute &#39;_check_plus_rune&#39;. Did you mean: &#39;_check_cross_rune&#39;?
 // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script>
      var CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "x1LLxmtngLheTvPt41D0";
    </script>
  </head>
  <body style="background-color: #fff">
    <div class="debugger">
<h1>AttributeError</h1>
<div class="detail">
  <p class="errormsg">AttributeError: &#39;Game&#39; object has no attribute &#39;_check_plus_rune&#39;. Did you mean: &#39;_check_cross_rune&#39;?
</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  <h3></h3>
  <ul><li><div class="frame" id="frame-1932605193616">
  <h4>File <cite class="filename">"C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1536</em>,
      in <code class="function">__call__</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>) -&gt; cabc.Iterable[bytes]:</pre>
<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;The WSGI server calls the Flask application object as the</pre>
<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>
<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>
<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;</pre>
<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)
<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre></div>
</div>

<li><div class="frame" id="frame-1932605193760">
  <h4>File <cite class="filename">"C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1514</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">                </span>error = e</pre>
<pre class="line current"><span class="ws">                </span>response = self.handle_exception(e)
<span class="ws">                </span>           ^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre>
<pre class="line after"><span class="ws">                </span>raise</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-1932605194048">
  <h4>File <cite class="filename">"C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1511</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws">        </span>error: BaseException | None = None</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()
<span class="ws">                </span>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>error = e</pre>
<pre class="line after"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre></div>
</div>

<li><div class="frame" id="frame-1932605193472">
  <h4>File <cite class="filename">"C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">919</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>request_started.send(self, _async_wrapper=self.ensure_sync)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line current"><span class="ws">            </span>rv = self.handle_user_exception(e)
<span class="ws">            </span>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre>
<pre class="line after"><span class="ws">        </span>self,</pre>
<pre class="line after"><span class="ws">        </span>rv: ft.ResponseReturnValue | HTTPException,</pre></div>
</div>

<li><div class="frame" id="frame-1932605193904">
  <h4>File <cite class="filename">"C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">917</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>request_started.send(self, _async_wrapper=self.ensure_sync)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line current"><span class="ws">                </span>rv = self.dispatch_request()
<span class="ws">                </span>     ^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre></div>
</div>

<li><div class="frame" id="frame-1932607144000">
  <h4>File <cite class="filename">"C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">902</em>,
      in <code class="function">dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>and req.method == &#34;OPTIONS&#34;</pre>
<pre class="line before"><span class="ws">        </span>):</pre>
<pre class="line before"><span class="ws">            </span>return self.make_default_options_response()</pre>
<pre class="line before"><span class="ws">        </span># otherwise dispatch to the handler for that endpoint</pre>
<pre class="line before"><span class="ws">        </span>view_args: dict[str, t.Any] = req.view_args  # type: ignore[assignment]</pre>
<pre class="line current"><span class="ws">        </span>return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def full_dispatch_request(self) -&gt; Response:</pre>
<pre class="line after"><span class="ws">        </span>&#34;&#34;&#34;Dispatches the request and on top of that performs request</pre>
<pre class="line after"><span class="ws">        </span>pre and postprocessing as well as HTTP exception catching and</pre>
<pre class="line after"><span class="ws">        </span>error handling.</pre></div>
</div>

<li><div class="frame" id="frame-1932607144144">
  <h4>File <cite class="filename">"D:\Pygame\geom\game_app\routes.py"</cite>,
      line <em class="line">65</em>,
      in <code class="function">next_action</code></h4>
  <div class="source "><pre class="line before"><span class="ws">    </span>return jsonify(game_logic.game.get_state())</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span>@main_routes.route(&#39;/api/game/next_action&#39;, methods=[&#39;POST&#39;])</pre>
<pre class="line before"><span class="ws"></span>def next_action():</pre>
<pre class="line before"><span class="ws">    </span>&#34;&#34;&#34;Processes the next single action in a turn.&#34;&#34;&#34;</pre>
<pre class="line current"><span class="ws">    </span>game_logic.game.run_next_action()
<span class="ws">    </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">    </span>return jsonify(game_logic.game.get_state())</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>@main_routes.route(&#39;/api/game/action_probabilities&#39;, methods=[&#39;GET&#39;])</pre>
<pre class="line after"><span class="ws"></span>def get_action_probabilities():</pre>
<pre class="line after"><span class="ws">    </span>&#34;&#34;&#34;</pre></div>
</div>

<li><div class="frame" id="frame-1932607144288">
  <h4>File <cite class="filename">"D:\Pygame\geom\game_app\game_logic.py"</cite>,
      line <em class="line">4083</em>,
      in <code class="function">run_next_action</code></h4>
  <div class="source "><pre class="line before"><span class="ws">        </span>teamId = action_info[&#39;teamId&#39;]</pre>
<pre class="line before"><span class="ws">        </span>is_bonus_action = action_info[&#39;is_bonus&#39;]</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span># Update all special structures for the current team right before it acts.</pre>
<pre class="line before"><span class="ws">        </span># This ensures the team acts based on its most current state.</pre>
<pre class="line current"><span class="ws">        </span>self._update_runes_for_team(teamId)
<span class="ws">        </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>self._update_prisms_for_team(teamId)</pre>
<pre class="line after"><span class="ws">        </span>self._update_trebuchets_for_team(teamId)</pre>
<pre class="line after"><span class="ws">        </span># We also re-update nexuses here mainly so the frontend display is accurate</pre>
<pre class="line after"><span class="ws">        </span># if a nexus is created or destroyed mid-turn. Bonus actions for this turn</pre>
<pre class="line after"><span class="ws">        </span># are already locked in from _start_new_turn.</pre></div>
</div>

<li><div class="frame" id="frame-1932607144432">
  <h4>File <cite class="filename">"D:\Pygame\geom\game_app\game_logic.py"</cite>,
      line <em class="line">4388</em>,
      in <code class="function">_update_runes_for_team</code></h4>
  <div class="source "><pre class="line before"><span class="ws">        </span>self.state[&#39;runes&#39;][teamId][&#39;trident&#39;] = self._check_trident_rune(teamId)</pre>
<pre class="line before"><span class="ws">        </span>self.state[&#39;runes&#39;][teamId][&#39;hourglass&#39;] = self._check_hourglass_rune(teamId)</pre>
<pre class="line before"><span class="ws">        </span>self.state[&#39;runes&#39;][teamId][&#39;star&#39;] = self._check_star_rune(teamId)</pre>
<pre class="line before"><span class="ws">        </span>self.state[&#39;runes&#39;][teamId][&#39;barricade&#39;] = self._check_barricade_rune(teamId)</pre>
<pre class="line before"><span class="ws">        </span>self.state[&#39;runes&#39;][teamId][&#39;t_shape&#39;] = self._check_t_rune(teamId)</pre>
<pre class="line current"><span class="ws">        </span>self.state[&#39;runes&#39;][teamId][&#39;plus_shape&#39;] = self._check_plus_rune(teamId)
<span class="ws">        </span>                                            ^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>self.state[&#39;runes&#39;][teamId][&#39;i_shape&#39;] = self._check_i_rune(teamId)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def _check_barricade_rune(self, teamId):</pre>
<pre class="line after"><span class="ws">        </span>&#34;&#34;&#34;</pre>
<pre class="line after"><span class="ws">        </span>Finds Barricade Runes: a rectangle with all four sides present as lines.</pre></div>
</div>
</ul>
  <blockquote>AttributeError: &#39;Game&#39; object has no attribute &#39;_check_plus_rune&#39;. Did you mean: &#39;_check_cross_rune&#39;?
</blockquote>
</div>

<div class="plain">
    <p>
      This is the Copy/Paste friendly version of the traceback.
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File &#34;C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py&#34;, line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py&#34;, line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py&#34;, line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py&#34;, line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py&#34;, line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py&#34;, line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;D:\Pygame\geom\game_app\routes.py&#34;, line 65, in next_action
    game_logic.game.run_next_action()
  File &#34;D:\Pygame\geom\game_app\game_logic.py&#34;, line 4083, in run_next_action
    self._update_runes_for_team(teamId)
  File &#34;D:\Pygame\geom\game_app\game_logic.py&#34;, line 4388, in _update_runes_for_team
    self.state[&#39;runes&#39;][teamId][&#39;plus_shape&#39;] = self._check_plus_rune(teamId)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: &#39;Game&#39; object has no attribute &#39;_check_plus_rune&#39;. Did you mean: &#39;_check_cross_rune&#39;?
</textarea>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\truon\miniconda3\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pygame\geom\game_app\routes.py", line 65, in next_action
    game_logic.game.run_next_action()
  File "D:\Pygame\geom\game_app\game_logic.py", line 4083, in run_next_action
    self._update_runes_for_team(teamId)
  File "D:\Pygame\geom\game_app\game_logic.py", line 4388, in _update_runes_for_team
    self.state['runes'][teamId]['plus_shape'] = self._check_plus_rune(teamId)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Game' object has no attribute '_check_plus_rune'. Did you mean: '_check_cross_rune'?

-->